# Generated by Django 4.2 on 2023-04-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='subject.subject'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='subject.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subject.chapter'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(),
        ),
    ]
